### ISSUE TITLE
Issue when running libtoolize

### ISSUE THREAD

**Issue by manasimahajann** [eduardobogoni/jlibfprint#4]
Error - libtoolize: `AC_PROG_RANLIB' is rendered obsolete by `LT_INIT'
Could you please help me with what needs to be done.
Thank you.

**Comment by manasimahajann** [comment]
Below error i get when i run ./autogen.sh

+ aclocal
./autogen.sh: 4: ./autogen.sh: aclocal: not found

Kindly help.

**Comment by eduardobogoni** [comment]
> Below error i get when i run ./autogen.sh
> 
>     aclocal
>     ./autogen.sh: 4: ./autogen.sh: aclocal: not found
> 
> Kindly help.

On Ubuntu "aclocal" seems provided by package "automake" (sudo apt-get install automake).

**Comment by manasimahajann** [comment]
Thank you for your reply! :) So now instead of libtoolize and ./autogen.sh - I should run "sudo apt-get install automake" ??

**Comment by mcoromac** [comment]
@manasimahajann I used this version instead: https://code.google.com/archive/p/jlibfprint/downloads
Inside there's a readme in which says it doesn't use libtoolize, rather just a makefile.

**Comment by eduardobogoni** [comment]
> Thank you for your reply! :) So now instead of libtoolize and ./autogen.sh - I should run "sudo apt-get install automake" ??

No, you need to install **aclocal** before try to build jlibfprint.
