### ISSUE TITLE
Greetings!

### ISSUE THREAD

**Issue by manasimahajann** [eduardobogoni/jlibfprint#5]
I ran all the commands, this time with out errors (except libtoolize)
on the last command that is - "java -cp target/jlibfprint-1.0-SNAPSHOT.jar  jlibfprint.SampleRun"
I get an error - "No device found to enroll fingers"
when it comes to the connections, are you using usb connector for TTL conversion or are you directly using serial comm pins - GPIO 14,15 on the board?
Sorry for the trouble.
Thank you!

**Comment by eduardobogoni** [comment]
> when it comes to the connections, are you using usb connector for TTL conversion or are you directly using serial comm pins - GPIO 14,15 on the board?

About 2014 I used a Persona 4000B (Or a compatible device) directly connected in the computer using USB 2 port. Today I has no more any device.

I believe you should test your device with [fprint demo](https://launchpad.net/ubuntu/xenial/+package/fprint-demo) before try jlibfprint. In https://www.freedesktop.org/wiki/Software/fprint/libfprint/Supported_devices/ there is a list of supported devices.

It works in fprint demo?

**Comment by manasimahajann** [comment]
Oh!! yes i am using ZFM20 fingerprint module with raspberry pi 3.
I don't see the zfm20 in the list you have provided.
The sensor works great with the PI Program - https://tutorials-raspberrypi.com/how-to-use-raspberry-pi-fingerprint-sensor-authentication/
We want it to be running in java. Anyway, thank you for taking some time out to reply.
Thank you! :)

**Comment by Awner** [comment]
Greetings again

I have a doubt about using jlibfprint, I used it to work with U are U fingerprint sensor and it works fine, but now I need to use it with another fingerprint device ( Upek Biometric Touchchip ) it's a capacitive sensor...

I test it with fprint-demo and it doesn't work... 

Jlibfprint backs an exception :

Enroll the first finger...
Enroll Exception [-22]
jlibfprint.JlibFprint$EnrollException


Do you know if i could use jlibfprint or I need to try with another solution?

Thanks for attention again!

**Comment by eduardobogoni** [comment]
> I have a doubt about using jlibfprint, I used it to work with U are U fingerprint sensor and it works fine, but now I need to use it with another fingerprint device ( Upek Biometric Touchchip ) it's a capacitive sensor...
> 
> I test it with fprint-demo and it doesn't work...

If it does not work with **fprint-demo** it is probably because **libfprint** does not support this device. Libfprint has a list of supported devices, check it: https://www.freedesktop.org/wiki/Software/fprint/libfprint/Supported_devices/.

If libfprint does not support your device there is not to do in **JLibfprint** because it just expose libfprint functions as a Java API - it does not change or add any functions. In this case you need - firstly - that libfprint support your device.
