### ISSUE TITLE
Comparing Prints...

### ISSUE THREAD

**Issue by fuantox** [eduardobogoni/jlibfprint#6]
Hey!
First of all thank you for making this code public!

I'm developping an application with lis library, and I'd really want to ask if there is a possible way to compare the print got from the reader with another stored in a DB.

Doing a little search in your code I found the method `img_compare_print_data` in JlibFprint.java, but it seems I can't just cast a `PrintData` to a `fp_print_data` type. 

Is there a way to make this method work?

Thanks in advance

**Comment by eduardobogoni** [comment]
In Java class PrintData there is a attribute "internalPointer". This attribute contains a address to a structure fp_print_data. Maybe there is a easy way to cast this pointer to the fp_print_data type required by JlibFprint.img_compare_print_data.

A more consistent way is implement a "compare" method in PrintData in project JlibFprint_jni.

**Comment by fuantox** [comment]
Thank you vey much for your answer!
I'll try doing what you told me in your comment, and write the results here for reference.

**Comment by NSnietol** [comment]
Hi @fuantox, were you able to compare the finger prints? I'm looking for a way to do that.
Thanks.
