### ISSUE TITLE
Exception on enrolling

### ISSUE THREAD

**Issue by mcoromac** [eduardobogoni/jlibfprint#8]
Hello, I'm getting this exception while trying to scan my finger:
```
Enroll the first finger...
Enroll Exception [3]
jlibfprint.JlibFprint$EnrollException

Process finished with exit code 0
```
I've tried multiple times but it always says the same. 
Here is my code: 
```
import jlibfprint.JlibFprint;
import jlibfprint.SampleRun;
import jlibfprint.JlibFprint.fp_enroll_result;

public class test {

    public static void main(String[] args) {
            JlibFprint jlibfprint = new JlibFprint();
            JlibFprint.fp_print_data pd1, pd2;
            int matchValue;
            try
            {
                System.out.println("Enroll the first finger...");
                pd1 = jlibfprint.enroll_finger();
                System.out.println("Compare the previous acquisition with the next one...");
                pd2 = jlibfprint.enroll_finger();
                matchValue = JlibFprint.img_compare_print_data(pd1, pd2);

                System.out.println(matchValue);
                if (matchValue > JlibFprint.BOZORTH_THRESHOLD)
                {
                    System.out.println("[OK] The two fingerprints are compatible!");
                }
                else
                {
                    System.out.println("[FAIL] The two fingerprints are not compatible!");
                }
            }
            catch (JlibFprint.EnrollException e)
            {
                System.err.format("Enroll Exception [%d]\n", e.enroll_exception);
                e.printStackTrace();
            }
        } catch (final Exception e) {
            //busses_project.log.error("Problem encountered", e);
            System.out.println("Failed");
        }
    }
}

```
Note: Just libfprint works fine with my fingerprint scanner so that discards a faulty driver or that my scanner is not supported. I'm using a Upek eikon.

**Comment by mcoromac** [comment]
If I'm not mistaken this Exception means "Enroll stage passed; more stages are need to complete the process." In C,  the enrolling process terminates after 3 readings but I don't know why with this library it only asks for one.

**Comment by eduardobogoni** [comment]
> If I'm not mistaken this Exception means "Enroll stage passed; more stages are need to complete the process." In C, the enrolling process terminates after 3 readings but I don't know why with this library it only asks for one.

By https://github.com/eduardobogoni/jlibfprint/blob/775295f08174d11d39da9e327120b128ef270fc4/JlibFprint_jni/src/jlibfprint_JlibFprint.cpp#L169-L172 seems JLibFprint does not deal with more than one-phase enroll: it just throws a exception if more than one enroll is required. Probably the developer had just a one-phase device and, as is, support your needs (Was my case).

**Comment by mcoromac** [comment]
I don't know exactly how the wrapper is done, I have no experience with that but I can learn.

I see that the library only has one method which is enroll_finger. And the C library has a bunch.
 
Any hints on how to start and fix this?

**Comment by eduardobogoni** [comment]
> I don't know exactly how the wrapper is done, I have no experience with that but I can learn.
> 
> I see that the library only has one method which is enroll_finger. And the C library has a bunch.
> 
> Any hints on how to start and fix this?

I believe that a good start point is try to fix **Java_jlibfprint_JlibFprint_enroll_1finger** to support more then one phase enroll:

https://github.com/eduardobogoni/jlibfprint/blob/775295f08174d11d39da9e327120b128ef270fc4/JlibFprint_jni/src/jlibfprint_JlibFprint.cpp#L143

**Comment by mcoromac** [comment]
Stupid mistake in my behalf. 
I was using another example of another library that was also called Jlibfprint. 

Note: This library does support more than one enrollment. And works with Upek Eikon fingerprint reader.

**Comment by hugobri** [comment]
Hi mcoromac,
I have the same problem, could you tell me how to solve it?

please
